name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # todos los días a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ lucas2mz }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          message: "generate contribution graph with snake"
          add: "dist/*.svg"
